name: Common Build Steps

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment name"
        required: true
        type: string
      source_branch:
        description: "Source branch name"
        required: true
        type: string
    secrets:
      #      CV_DATA_JS_CONTENT:
      #        description: "Base64 encoded CV data"
      #        required: true
      #      GITHUB_TOKEN:
      #        description: "GitHub token"
      #        required: true
      CV_HOSTING_HOOK:
        description: "Hosting hook URL"
        required: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.source_branch }}

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create data directory
        run: mkdir -p dist/data

      - name: Create JSON file
        run: echo "${{ secrets.CV_DATA_JS_CONTENT }}" | base64 -d > dist/data/cv.json

      - name: Push to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: ${{ inputs.environment == 'test' && 'build-test' || 'build' }}
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg} [env:${{ inputs.environment }} from:${{ inputs.source_branch }}]"

      - name: Trigger hosting hook
        if: success()
        run: curl -X POST "${{ secrets.CV_HOSTING_HOOK }}"