name: Deploy to Test

on:
  push:
    branches: [ develop ]
    paths-ignore: # Add paths to ignore
      - '**.md'
      - '.gitignore'
      - '.editorconfig'
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch'
        required: true
        default: 'develop'
        type: string

jobs:
  deploy-test:
    uses: ./.github/workflows/common.yml
    with:
      environment: 'test'
      source_branch: ${{ github.event_name == 'workflow_dispatch' && inputs.source_branch || vars.DEFAULT_SOURCE_BRANCH }}
    secrets: inherit    # Simplify secrets passing
