name: Generate a build and push to another branch

on:
  push:
    branches:
      - main # The branch name you are commit the new changes

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Create JSON file
        run: echo "${{ secrets.CV_DATA_JS_CONTENT }}" | base64 -d > data/cv.json

      - name: Build
        run: npm run build # The build command of your project

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name with the assets
          FOLDER: dist # The directory with the generated assets
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}" # The commit message